//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Exp00069.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_EDIT_DMLV                   101
#define IDC_EDIT_LVCX                   102
#define IDD_EDITDB00                    102
#define IDC_EDIT_LVCY                   103
#define IDD_DMLV                        103
#define IDD_BUILDLABU                   104
#define IDR_MAINFRAME                   128
#define IDR_EXP000TYPE                  129
#define IDR_DMTELE                      130
#define IDR_SHOWCASE                    131
#define IDR_DMLV                        132
#define IDB_FRAGMENT                    135
#define IDR_EDITLV                      136
#define IDR_OBJEXP                      141
#define IDR_OBJVIEW                     147
#define IDD_EDITDBITEM                  148
#define IDD_EDITDB01                    149
#define IDD_EDITDB02                    151
#define IDD_EDITDB03                    152
#define IDD_EDITDB04                    153
#define IDD_EDITDB05                    154
#define IDD_EDITDB06                    155
#define IDD_EDITDB07                    156
#define IDD_EDITDB08                    157
#define IDD_EDITDB09                    158
#define IDD_EDITDB10                    159
#define IDD_EDITDB11                    160
#define IDD_EDITDB12                    161
#define IDD_EDITDB13                    162
#define IDD_EDITDB14                    163
#define IDD_EDITDB15                    164
#define IDD_EDITTILE                    167
#define IDD_EDITROOTSEL                 167
#define IDD_EDITLVDESC                  168
#define IDD_EDITDMFILEDESC              169
#define IDR_DMHEXEDIT                   170
#define IDD_EDITLVDESC2                 173
#define IDB_TILE01                      174
#define IDB_TILE02                      175
#define IDB_TILE03                      176
#define IDB_TILE04                      177
#define IDB_TILE05                      178
#define IDB_TILE06                      179
#define IDB_TILE07                      180
#define IDB_TILE08                      181
#define IDB_TILE09                      182
#define IDB_TILE10                      183
#define IDB_TILE11                      184
#define IDB_TILE12                      185
#define IDB_TILE13                      186
#define IDB_TILE14                      187
#define IDB_TILE15                      188
#define IDB_TILE16                      189
#define IDB_TILE17                      190
#define IDB_TILE18                      191
#define IDB_TILE19                      192
#define IDB_TILE20                      193
#define IDB_TILE21                      194
#define IDB_TILE22                      195
#define IDB_TILE23                      196
#define IDB_TILE24                      197
#define IDB_HATCHMASK                   198
#define IDB_HATCH_HIDMASK               230
#define IDB_CHIP_CHES                   233
#define IDB_CHIP_CLOT                   234
#define IDB_CHIP_MISC                   235
#define IDB_CHIP_POTI                   236
#define IDB_CHIP_SCRO                   237
#define IDB_CHIP_WEAP                   238
#define IDB_RP_0                        239
#define IDB_RP_1                        240
#define IDB_RP_2                        241
#define IDB_RP_3                        242
#define IDB_TP_N                        243
#define IDB_TP_E                        244
#define IDB_TP_S                        245
#define IDB_TP_W                        246
#define IDD_EDIT_TILEPROP               247
#define IDB_ORNATE_F0                   248
#define IDB_ORNATE_W0                   249
#define IDB_ORNATE_W1                   250
#define IDB_CREATURE                    251
#define IDB_TILE_4WAY                   252
#define IDB_PT_1                        254
#define IDR_DM2ITEMLIST                 257
#define IDD_TILE_PIT                    260
#define IDD_TILE_STAIRS                 261
#define IDD_TILE_DOOR                   262
#define IDD_TILE_TELE                   263
#define IDD_TILE_FALSE                  264
#define IDD_TILE_NO                     265
#define IDD_PI_CREATURE                 266
#define IDD_PI_WEAPON                   267
#define IDD_PI_CLOTH                    269
#define IDD_PI_SCROLL                   270
#define IDD_PI_POTION                   271
#define IDD_PI_CHEST                    272
#define IDD_PI_MISC                     273
#define IDD_PI_TEXT                     275
#define IDD_PI_ACTU1                    276
#define IDD_PI_ACTU2                    277
#define IDD_PI_ACTU3                    279
#define IDD_PI_NO                       280
#define IDD_PI_TELE                     284
#define IDD_PI_DOOR                     290
#define IDB_ORNATE_D0                   293
#define IDB_DOOR0                       294
#define IDD_SEL_ORNATE                  295
#define IDD_EDITDMFILEDESC2             296
#define IDD_EDITLVDESC3                 298
#define IDR_RTF_ABOUT                   300
#define IDB_BLACK                       301
#define IDD_WORLD_SHIFT                 302
#define IDI_AR_UP                       303
#define IDI_AR_LEFT                     304
#define IDI_AR_RIGHT                    305
#define IDI_AR_DOWN                     306
#define IDB_SPLASH                      308
#define IDD_SPLASH                      311
#define IDI_INVMARK                     315
#define IDD_TEXTINPUT                   316
#define IDD_PI_TEXT2                    317
#define IDR_RTF_SHORTCUTS               320
#define IDD_SETTLE                      321
#define IDR_RTF_DND                     322
#define IDD_PI_ACTUHINT                 322
#define IDR_RTF_TILEPROP                323
#define IDR_ACTUHINT                    325
#define IDB_GETBACK                     326
#define IDC_H_POINT                     327
#define IDC_H_MOVE                      328
#define IDR_RTF_CHANGES                 329
#define IDR_FINDER                      332
#define IDD_FINDER_INPUT                334
#define IDR_RTF_FINDERVW                335
#define IDC_SPIN_DMLV                   1001
#define IDC_SPIN_LVCX                   1003
#define IDC_SPIN_LVCY                   1005
#define IDC_EDIT_LVMAX                  1006
#define IDC_SPIN_LVMAX                  1007
#define IDC_TAB_DBSEL                   1007
#define IDC_EDIT_W00                    1011
#define IDC_EDIT_W01                    1012
#define IDC_EDIT_W02                    1013
#define IDC_EDIT_W03                    1014
#define IDC_EDIT_W04                    1015
#define IDC_EDIT_W5                     1016
#define IDC_EDIT_W6                     1017
#define IDC_EDIT_P01                    1018
#define IDC_EDIT_P02                    1019
#define IDC_EDIT_P03                    1020
#define IDC_EDIT_P04                    1021
#define IDC_EDIT_P05                    1022
#define IDC_EDIT_P06                    1023
#define IDC_EDIT_P07                    1024
#define IDS_ERR_INVALID_CHECK_SUM       1024
#define IDC_EDIT_P08                    1025
#define IDC_COMBO_ALIGN                 1026
#define IDC_COMBO_NEXT_ITEM             1027
#define IDC_STATIC_LVCY                 1029
#define IDC_STATIC_LVCX                 1030
#define IDS_FONTTEMP_DMOBBAR            1031
#define IDC_STATIC_ALIGNMENT            1031
#define IDS_FONTTEMP_DMOBTREEVIEW       1032
#define IDC_CHECK_HEX                   1032
#define IDS_FONTTEMP_VIEW               1033
#define IDC_CHECK_REMEMBER_HEX          1033
#define IDS_WARN_DANGEROUS_TO_INSERT    1034
#define IDC_STATIC_NEXT_ITEM            1034
#define IDS_FONTTEMP_DMLVSEL            1035
#define IDC_STATIC_LVDESC_APPLY         1035
#define IDC_STATIC_LVDESC_RESET         1036
#define IDP_PARSE_XDIGIT                1036
#define IDC_EDIT_TILE_VAL               1037
#define IDS_FONTTEMP_DMHEXEDIT          1037
#define IDC_EDIT_SHIFTX                 1038
#define IDS_FONTTEMP_DMCITREEVIEW       1038
#define IDC_EDIT_SHIFTY                 1039
#define IDS_ERR_DB_AT_MAX_CAP           1039
#define IDC_EDIT_W2                     1040
#define IDS_STR_FAIL_LOAD_ORNATES       1040
#define IDC_EDIT_W4                     1041
#define IDS_WARN_OPTS                   1041
#define IDC_EDIT_ALTITUDE               1042
#define IDS_STR_FAIL_LOAD_NAME_TBL      1042
#define IDC_EDIT_MAP_WIDTH              1043
#define IDS_WARN_OPTS_FLATTEN           1043
#define IDC_EDIT_MAP_HEIGHT             1044
#define IDS_ERR_OPT_FLATTEN             1044
#define IDC_EDIT_10_0_3                 1045
#define IDS_ERR_OPT_FLATTEN_GEN         1045
#define IDC_EDIT_10_4_7                 1046
#define IDS_ERR_OPT_FLATTEN_OOR         1046
#define IDC_EDIT_10_8_B                 1047
#define IDS_OK_OPTS                     1047
#define IDC_EDIT_10_C_F                 1048
#define IDS_FONTTEMP_TEXTINPUT          1048
#define IDC_EDIT_WALL_DECO              1049
#define IDS_ERR_DBFULL                  1049
#define IDC_EDIT_MONSTERS               1050
#define IDS_FONTTEMP_EXTTEXT            1050
#define IDC_EDIT_12_8_B                 1051
#define IDS_ERR_SETTLE_TRANSIT          1051
#define IDC_EDIT_12_C_F                 1052
#define IDS_ERR_URL_OF_INTERNET         1052
#define IDC_EDIT_14_0_3                 1053
#define IDS_WARN_COLLECT_SAMPLES        1053
#define IDC_EDIT_14_4_7                 1054
#define IDS_WARN_UNLIMITED_MODE         1054
#define IDC_EDIT_14_8_B                 1055
#define IDS_ASK_WOULD_YOU_OPEN          1055
#define IDC_EDIT_14_C_F                 1056
#define IDS_FONTTEMP_FINDERVW           1056
#define IDS_MOVE2ACTU_DONE              1057
#define IDS_ERR_KILL_RECORD11           1058
#define IDC_EDIT_RGS                    1060
#define IDC_EDIT_TEXT_DATA              1061
#define IDC_EDIT_SPP                    1062
#define IDC_EDIT_SPP_X                  1062
#define IDC_EDIT_MOLS                   1063
#define IDC_EDIT_SPP_Y                  1064
#define IDC_EDIT_TOTALMAPCNT            1065
#define IDC_COMBO_PLAYERDIR             1066
#define IDC_LIST_ITEMS                  1068
#define IDC_COMBO_TYPE                  1069
#define IDC_COMBO_OBJ                   1070
#define IDC_BUTTON_RECORD_INSERT_BEFORE 1072
#define IDC_BUTTON_RECORD_INSERT_AFTER  1073
#define IDC_BUTTON_RECORD_APPEND        1074
#define IDC_BUTTON_RECORD_REMOVE        1075
#define IDC_BUTTON_RECORD_CLONE         1076
#define IDC_BUTTON_RECORD_ADD_SUB_FIRST 1077
#define IDC_BUTTON_RECORD_ADD_SUB_LAST  1078
#define IDC_CHECK_DIR_N                 1081
#define IDC_CHECK_DIR_E                 1082
#define IDC_CHECK_DIR_S                 1083
#define IDC_CHECK_DIR_W                 1084
#define IDC_TAB_DETAIL                  1086
#define IDC_CHECK_SW1                   1093
#define IDC_CHECK_SW2                   1094
#define IDC_CHECK_SW3                   1095
#define IDC_CHECK_SW4                   1096
#define IDC_CHECK_SW5                   1097
#define IDC_CHECK_SW6                   1098
#define IDC_CHECK_SW7                   1099
#define IDC_CHECK_SW8                   1100
#define IDC_RADIO_OP1                   1101
#define IDC_RADIO_OP2                   1102
#define IDC_RADIO_OP3                   1103
#define IDC_RADIO_OP4                   1104
#define IDC_RADIO_OP5                   1105
#define IDC_RADIO_OP6                   1106
#define IDC_RADIO_OP7                   1107
#define IDC_RADIO_OP8                   1108
#define IDC_EDIT_VALUE                  1112
#define IDC_SPIN_VALUE                  1113
#define IDC_COMBO_CREATURE              1115
#define IDC_COMBO_WEAPON                1116
#define IDC_COMBO_N_CHARGES             1117
#define IDC_COMBO_CLOTH                 1128
#define IDC_COMBO_TEXT                  1129
#define IDC_COMBO_POTION                1131
#define IDC_SLIDER_STR                  1132
#define IDC_COMBO_CHEST                 1133
#define IDC_COMBO_MISC                  1134
#define IDC_COMBO_STATE                 1135
#define IDC_COMBO_ITEM_TYPE             1141
#define IDC_COMBO_ITEM_NAME             1142
#define IDC_EDIT_N                      1143
#define IDC_SPIN_N                      1144
#define IDC_COMBO_MISSILE               1145
#define IDC_EDIT_LOARG                  1146
#define IDC_COMBO_HERO                  1147
#define IDC_CHECK_SW_IS_ON              1148
#define IDC_SPIN_LOARG                  1148
#define IDC_EDIT_HIARG                  1149
#define IDC_RADIO_AT_ON                 1150
#define IDC_SPIN_HIARG                  1150
#define IDC_RADIO_AT_OFF                1151
#define IDC_RADIO_AT_TOGGLE             1152
#define IDC_RADIO_AT_LINK               1153
#define IDC_CHECK_INVERSE               1154
#define IDC_CHECK_BEEP                  1155
#define IDC_EDIT_DELAY                  1156
#define IDC_SPIN_DELAY                  1157
#define IDC_COMBO_ORNATE                1158
#define IDC_EDIT_X                      1159
#define IDC_EDIT_Y                      1160
#define IDC_EDIT_MAP                    1161
#define IDC_BUTTON_REF                  1162
#define IDC_BUTTON_SELF                 1163
#define IDC_TAB                         1168
#define IDC_STATIC_ITEM                 1169
#define IDC_STATIC_COUNT                1170
#define IDC_STATIC_MISSILE              1171
#define IDC_STATIC_CREATURE             1172
#define IDC_STATIC_HERO                 1173
#define IDC_STATIC_LOCATOR              1174
#define IDC_STATIC_CREATURE_AI          1174
#define IDC_STATIC_STR                  1175
#define IDC_COMBO_DIR                   1176
#define IDC_STATIC_MAP                  1177
#define IDC_STATIC_ORNATE_PREVIEW       1178
#define IDC_RADIO_TAR1                  1184
#define IDC_RADIO_TAR2                  1185
#define IDC_RADIO_TAR3                  1186
#define IDC_RADIO_TAR4                  1187
#define IDC_RADIO_ROT1                  1188
#define IDC_RADIO_ROT2                  1189
#define IDC_RADIO_ROT3                  1190
#define IDC_RADIO_ROT4                  1191
#define IDC_RADIO_ROT5                  1192
#define IDC_RADIO_ROT6                  1193
#define IDC_RADIO_ROT7                  1194
#define IDC_RADIO_ROT8                  1195
#define IDC_CHECK_DOOR_TYPE             1197
#define IDC_CHECK_VERT                  1200
#define IDC_CHECK_DOOR_BUTTON           1201
#define IDC_CHECK_DESTROY_OK            1202
#define IDC_CHECK_BASH_OK               1203
#define IDC_COMBO_DOOR                  1204
#define IDC_EDIT_SEED                   1207
#define IDC_EDIT_WIDTH                  1212
#define IDC_EDIT_HEIGHT                 1213
#define IDC_EDIT_DEPTH                  1214
#define IDC_COMBO_SCENE                 1215
#define IDC_COMBO_WO                    1216
#define IDC_COMBO_FO                    1217
#define IDC_COMBO_DO                    1218
#define IDC_COMBO_DS                    1219
#define IDC_EDIT_DIFFICULTY             1220
#define IDC_BUTTON_REPLACE_WO           1221
#define IDC_BUTTON_REPLACE_FO           1222
#define IDC_BUTTON_REPLACE_DO           1223
#define IDC_BUTTON_REPLACE_CS           1224
#define IDC_BUTTON_RT_WO                1226
#define IDC_BUTTON_RT_FO                1227
#define IDC_RADIO_V0                    1227
#define IDC_BUTTON_RT_DO                1228
#define IDC_RADIO_V1                    1228
#define IDC_EDIT_CNT_MAPS               1228
#define IDC_RADIO_V2                    1229
#define IDC_SPIN_CNT_MAP                1229
#define IDC_BUTTON_RT_CS                1229
#define IDC_RADIO_V3                    1230
#define IDC_COMBO_CS                    1230
#define IDC_RADIO_V4                    1231
#define IDC_RADIO_V5                    1232
#define IDC_CHECK_V1                    1232
#define IDC_RADIO_V6                    1233
#define IDC_CHECK_V2                    1233
#define IDC_RICHEDIT_HINT               1233
#define IDC_RADIO_V7                    1234
#define IDC_CHECK_V3                    1234
#define IDC_CHECK_V4                    1235
#define IDC_CHECK_V5                    1236
#define IDC_SPIN_X                      1237
#define IDC_SPIN_Y                      1238
#define IDC_SPIN_WIDTH                  1239
#define IDC_SPIN_HEIGHT                 1240
#define IDC_SPIN_DEPTH                  1241
#define IDC_SPIN_DIFFICULTY             1242
#define IDC_TREE_CLASSES                1245
#define IDC_STATIC_HINT                 1250
#define IDC_EDIT_MESSAGE                1251
#define IDC_COMBO_SEL                   1252
#define IDC_LIST_TEXT                   1253
#define IDC_COMBO1                      1254
#define IDC_COMBO_USE                   1254
#define IDC_CHECK_N0                    1255
#define IDC_CHECK_N1                    1256
#define IDC_CHECK_N2                    1257
#define IDC_CHECK_N3                    1258
#define IDC_CHECK_N4                    1259
#define IDC_CHECK_N5                    1260
#define IDC_CHECK_N6                    1261
#define IDC_CHECK_N7                    1262
#define IDC_CHECK_N8                    1263
#define IDC_CHECK_N9                    1264
#define IDC_CHECK_N10                   1265
#define IDC_CHECK_N11                   1266
#define IDC_CHECK_N12                   1267
#define IDC_CHECK_N13                   1268
#define IDC_CHECK_N14                   1269
#define IDC_CHECK_N15                   1270
#define IDC_CHECK_N16                   1271
#define IDC_STATIC_USE_TYPE             1273
#define IDC_STATIC_TEXT                 1276
#define IDC_RADIOM1                     1277
#define IDC_RADIOM2                     1278
#define IDC_STATIC_USE                  1278
#define IDC_EDIT_SP                     1280
#define IDC_SPIN_SP                     1281
#define IDC_STATIC_SP                   1282
#define IDC_RADIO_DOOR1                 1283
#define IDC_RADIO_DOOR2                 1284
#define IDC_BUTTON_SETTLE               1286
#define IDC_STATIC_STATE                1287
#define IDC_CHECK_TIMER                 1288
#define IDC_BUTTON_UPDATE               1290
#define IDC_STATIC_WARN                 1291
#define IDC_RADIO1                      1292
#define IDC_RADIO2                      1293
#define IDC_RADIO3                      1294
#define IDC_BUTTON_SAVE                 1295
#define IDC_RICHEDIT_HELP               1296
#define IDC_STATIC_MT                   1298
#define IDC_STATIC_DELAY                1299
#define IDC_STATIC_WCAREA               1301
#define IDC_BUTTON_EDIT                 1302
#define IDC_BUTTON_SAMPLER              1303
#define IDC_STATIC_VER                  1305
#define IDC_RADIO_KABE_TAOSHI           1314
#define IDC_RADIO_ANAHORI               1315
#define IDC_EDIT_RETIRE                 1316
#define IDC_SPIN_RETIRE                 1317
#define IDC_CHECK_TRAP                  1318
#define ID_POPUP_ALL_DB0                32600
#define ID_POPUP_ALL_DB1                32601
#define ID_POPUP_ALL_DB2                32602
#define ID_POPUP_ALL_DB3                32603
#define ID_POPUP_ALL_DB4                32604
#define ID_POPUP_ALL_DB5                32605
#define ID_POPUP_ALL_DB6                32606
#define ID_POPUP_ALL_DB7                32607
#define ID_POPUP_ALL_DB8                32608
#define ID_POPUP_ALL_DB9                32609
#define ID_POPUP_ALL_DB10               32610
#define ID_POPUP_ALL_DB11               32611
#define ID_POPUP_ALL_DB12               32612
#define ID_POPUP_ALL_DB13               32613
#define ID_POPUP_ALL_DB14               32614
#define ID_POPUP_ALL_DB15               32615
#define ID_VIEW_DICTREE                 32616
#define ID_VIEW_BROWSE_BACK             32617
#define ID_VIEW_BROWSE_FORWARD          32618
#define ID_WND_DMLV                     32771
#define ID_WND_LVCX                     32772
#define ID_WND_LVCY                     32773
#define ID_BTN_CURSOR                   32775
#define ID_BTN_N1                       32776
#define ID_BTN_N2                       32777
#define ID_BTN_N3                       32778
#define ID_BTN_N4                       32779
#define ID_BTN_N5                       32780
#define ID_BTN_N6                       32781
#define ID_BTN_N7                       32782
#define ID_BTN_N8                       32783
#define ID_BTN_ERASE_TILE_REC           32784
#define ID_VIEW_SIZE1X                  32789
#define ID_VIEW_SIZE2X                  32790
#define ID_VIEW_SIZE4X                  32791
#define ID_POPUP_INSERT_ITEM_BEFORE     32809
#define ID_POPUP_INSERT_ITEM_AFTER      32810
#define ID_POPUP_EDIT_ITEM_HERE         32811
#define ID_POPUP_DELETE_ITEM_HERE       32812
#define ID_POPUP_REMOVE_ALL_SUB         32813
#define ID_POPUP_INSERT_ITEM_FIRST      32814
#define ID_POPUP_INSERT_ITEM_LAST       32815
#define ID_POPUP_INSERT_SUBITEM_FIRST   32821
#define ID_POPUP_INSERT_SUBITEM_LAST    32822
#define ID_APP_DEV                      32823
#define ID_BTN_B0                       32824
#define ID_BTN_B1                       32825
#define ID_BTN_B2                       32826
#define ID_BTN_B3                       32827
#define ID_BTN_B10                      32828
#define ID_EDIT_LVDESC                  32829
#define ID_POPUP_LIMITLESS              32836
#define ID_POPUP_INSERT_ITEM_FIRST_APPEND 32839
#define ID_POPUP_INSERT_ITEM_LAST_APPEND 32840
#define ID_POPUP_INSERT_ITEM_BEFORE_APPEND 32844
#define ID_POPUP_INSERT_ITEM_AFTER_APPEND 32845
#define ID_POPUP_EXCEPT_ITEM            32847
#define ID_POPUP_INSERT_SUBITEM_FIRST_APPEND 32848
#define ID_POPUP_INSERT_SUBITEM_LAST_APPEND 32849
#define ID_POPUP_BT_ITEM_HERE           32850
#define ID_VIEW_FORCE_HEX_TILE          32857
#define ID_APP_CLOSE                    32858
#define ID_EDIT_DMFILEDESC              32859
#define ID_FILE_APPLY                   32860
#define ID_EDIT_REPAIR_5THBIT           32862
#define ID_EDIT_OPTIMIZE                32863
#define ID_OPT_SAVE_LE                  32864
#define ID_OPT_ATTACH_CS                32866
#define ID_EDIT_CHECK_INTEGRITY         32867
#define ID_EDIT_UNDUPLICATE_DB          32869
#define ID_EDIT_OPTIMIZE_FLAT           32869
#define ID_CONTEXT_COPY_SUB             32870
#define ID_CONTEXT_COPY_SUB_SIB         32871
#define ID_CONTEXT_PASTE_AT_LAST        32872
#define ID_CONTEXT_PASTE_AT_FIRST       32873
#define ID_CONTEXT_PASTE_AFTER          32874
#define ID_CONTEXT_PASTE_BEFORE         32875
#define ID_CONTEXT_PASTE_AT_FIRST_IN_SUB 32876
#define ID_CONTEXT_PASTE_AT_LAST_IN_SUB 32877
#define ID_VIEW_DISPLAY_TILE_VAL        32888
#define ID_EDIT_ADD_MAP                 32889
#define ID_VIEW_DEV                     32893
#define ID_VIEW_TLV0                    32894
#define ID_VIEW_TLV1                    32895
#define ID_VIEW_TLV2                    32896
#define ID_VIEW_TLV3                    32897
#define ID_VIEW_TLVX                    32898
#define ID_VIEW_TI_NORM                 32899
#define ID_VIEW_TI_BACKTRACE            32900
#define ID_VIEW_TL_DEEPBACK             32901
#define ID_VIEW_TL_MAX                  32909
#define ID_OPT_RELOAD_ORNATES           32910
#define ID_EDIT_MK_TOPVW                32911
#define ID_OPT_RELOAD_DIC               32912
#define ID_EDIT_ROTX_P                  32913
#define ID_EDIT_ROTY_P                  32914
#define ID_EDIT_ROTX_N                  32915
#define ID_EDIT_ROTY_N                  32916
#define ID_EDIT_WORLD_SHIFT             32917
#define ID_DIR_N                        32921
#define ID_DIR_E                        32922
#define ID_DIR_S                        32923
#define ID_DIR_W                        32924
#define ID_OPT_SETTLE                   32926
#define ID_HELP_SHOWCASE                32927
#define ID_AHMT_ITEMTYPE                32928
#define ID_AHMT_ITEMITEM                32929
#define ID_AHMT_COUNT                   32930
#define ID_AHMT_MISSILE                 32931
#define ID_AHMT_CREATURE                32932
#define ID_AHMT_HERO                    32933
#define ID_AHMT_ORNATE                  32934
#define ID_AHMT_SW                      32935
#define ID_AHMT_MESSAGETYPE             32936
#define ID_AHMT_INVERSE                 32937
#define ID_AHMT_BEEP                    32938
#define ID_AHMT_DELAY                   32939
#define ID_AHMT_LOCATOR                 32940
#define ID_AHMT_STR                     32941
#define ID_CONTEXT_EDIT_FP              32951
#define ID_CONTEXT_EDIT_NOTEPAD         32952
#define ID_BUTTON_GET_BACK              32953
#define ID_REFRESH_PROPERTY_PAGE        32954
#define ID_FINDER_FIND                  32957
#define ID_FINDER_ONECLICK              32958
#define ID_HELP_FINDERVW                32960
#define ID_VIEW_SNAP_TO_TL              32961
#define ID_DEBUG_MOVE2ACTU2             32963
#define ID_OPT_CHECK_LEVEL_DESC         32965
#define ID_EDIT_BUILDLABYRINTH          32966
#define ID_OPT_DM2_EXTENDED_MAP         32967
#define ID_OPT_ASSETS_DM2               32970
#define ID_OPT_ASSETS_DM2BETA           32971
#define IDW_DIALOGBAR                   59397
#define IDW_EDITLVBAR                   59398
#define IDW_DMOBBAR                     59399
#define IDW_DMLVSELBAR                  59400
#define IDW_DMCIBAR                     59401
#define IDW_DMLVSEL2BAR                 59402
#define IDW_DMMAPSEL2BAR                59403
#define IDW_SHOWCASEBAR                 59404
#define IDW_FINDERBAR                   59405

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        336
#define _APS_NEXT_COMMAND_VALUE         32972
#define _APS_NEXT_CONTROL_VALUE         1319
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
