#!/bin/bash
## Compile all V4KJ9821 code

## SYS CORE
./XCOMP.sh DME
./XCOMP.sh KMOUSE
./XCOMP.sh KFILESET
./XCOMP.sh SKDOS
./XCOMP.sh SKMIDI
./XCOMP.sh SKDEBUG
./XCOMP.sh SKGLOBAL
./XCOMP.sh SKMEM

./XCOMP.sh KGFX
./XCOMP.sh KSFX


## MAIN GAME
./XCOMP.sh SKPARAM
./XCOMP.sh KGDAT
./XCOMP.sh KUI
./XCOMP.sh KEVENT
./XCOMP.sh KCHMPION
./XCOMP.sh KITEM
./XCOMP.sh KCREATUR
./XCOMP.sh KENVIRON
./XCOMP.sh KTEXT
./XCOMP.sh KWEATHER
./XCOMP.sh KDUNG
./XCOMP.sh KGAME
./XCOMP.sh KGUIDRW

## EXTRA
./XCOMP6.sh XCOREENH
./XCOMP6.sh XCOREDM1
./XCOMP6.sh XCOREEXT
./XCOMP6.sh XCORELOG
./XCOMP.sh KCOREDUN
./XCOMPW.sh KCORE
gcc -w -o SKLUA.o -c SKLUA.cpp -I. -I../../lua/include -I../v6spxmex -D__LINUX__ -DSK9821V4 -D__SK_NO_ALLEGRO__ 
